id = "vscode-classics"
name = "VS Code Classics"
version = "0.2.0"
schema_version = 1
authors = ["Alan <alanisme.my@gmail.com>"]
description = "❤️ All 17 built-in Visual Studio Code color themes, ported to Zed."
repository = "https://github.com/alanisme/vscode-themes-for-zed"
